moving multiheadattention out of modules
pytorch/text pull request #1267
Opened 2021-03-31 03:15 UTC by parmeet

Moving multiheadattention module out of modules. This will change the documentation from torchtext.nn.modules.multiheadattention to torchtext.nn.multiheadattention

2021-03-31 13:50 UTC, zhangguanheng66 requested changes
If we decide to move this out of the `nn` folder, just remember to have a comprehensive check for the `examples` folder.

2021-03-31 15:59 UTC, cpuhrsch requested changes
We should still preserve the torchtext.nn.modules.multiheadattention path, because we already have it, so I'd leave the folder structure (torchtext/nn/modules) as is, but add an init file under (torchtext/nn) to enable torchtext.nn.MultiheadAttentionContainer etc. Note that right now the new path would be torchtext.nn.multiheadattention.MultiheadAttentionContainer

2021-03-31 16:07 UTC, zhangguanheng66 commented
> We should still preserve the torchtext.nn.modules.multiheadattention path, because we already have it, so I'd leave the folder structure (torchtext/nn/modules) as is, but add an init file under (torchtext/nn) to enable torchtext.nn.MultiheadAttentionContainer etc. Note that right now the new path would be torchtext.nn.multiheadattention.MultiheadAttentionContainer

We should leave a warning for the current users and instruct them to switch to the new path.

2021-03-31 16:34 UTC, parmeet commented
> We should still preserve the torchtext.nn.modules.multiheadattention path, because we already have it, so I'd leave the folder structure (torchtext/nn/modules) as is, but add an init file under (torchtext/nn) to enable torchtext.nn.MultiheadAttentionContainer etc. Note that right now the new path would be torchtext.nn.multiheadattention.MultiheadAttentionContainer

ahh, got it. Thanks for clarification! Let me do the changes accordingly.

2021-03-31 17:35 UTC, parmeet commented
> > We should still preserve the torchtext.nn.modules.multiheadattention path, because we already have it, so I'd leave the folder structure (torchtext/nn/modules) as is, but add an init file under (torchtext/nn) to enable torchtext.nn.MultiheadAttentionContainer etc. Note that right now the new path would be torchtext.nn.multiheadattention.MultiheadAttentionContainer
> 
> We should leave a warning for the current users and instruct them to switch to the new path.

@zhangguanheng66  basically the symbols are already imported in the __init__.py of torchtext.nn and hence are already available both from torchtext.nn as well as torchtext.nn.modules. So do you mean if the user is importing them as 
`from torchtext.nn.modules import MultiheadAttentionContainer ` we should raise warning to switch to torch.nn import?

2021-03-31 18:06 UTC, zhangguanheng66 commented
> > > We should still preserve the torchtext.nn.modules.multiheadattention path, because we already have it, so I'd leave the folder structure (torchtext/nn/modules) as is, but add an init file under (torchtext/nn) to enable torchtext.nn.MultiheadAttentionContainer etc. Note that right now the new path would be torchtext.nn.multiheadattention.MultiheadAttentionContainer
> > 
> > 
> > We should leave a warning for the current users and instruct them to switch to the new path.
> 
> @zhangguanheng66 basically the symbols are already imported in the **init**.py of torchtext.nn and hence are already available both from torchtext.nn as well as torchtext.nn.modules. So do you mean if the user is importing them as
> `from torchtext.nn.modules import MultiheadAttentionContainer ` we should raise warning to switch to torch.nn import?

For example
```
from torchtext.nn.modules import MultiheadAttentionContainer
```
They should have a warning to remove `modules`.

2021-04-01 14:23 UTC, cpuhrsch approved these changes

2021-04-01 14:43 UTC, merged